name: delete-preview

on:
  pull_request_target:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v5
        with:
          ref: gh-pages

      - name: Delete preview files
        run: |
          rm -rf _preview/${{ github.event.pull_request.number }}

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          branch: gh-pages
          commit_message: "Delete preview for pull request #${{ github.event.pull_request.number }}"
